### ISSUE TITLE
map CSV file to RDS

### ISSUE THREAD

**Issue by cleemansen** [movestore/cloud-provider-download#2]
we should remove the CSV handling in the SDK during *reading* and move the logic to this app.

```
input <- tryCatch({
        # 1: try to read input as move RDS file
        readRDS(file = sourceFile)
      },
      error = function(readRdsError) {
        tryCatch({
          # 2 (fallback): try to read input as move CSV file
          move::move(sourceFile, removeDuplicatedTimestamps=TRUE)
        },
        error = function(readCsvError) {
          # collect errors for report and throw custom error
          stop(paste(sourceFile, " -> readRDS(sourceFile): ", readRdsError, "move(sourceFile): ", readCsvError, sep = ""))
        })
      })
```

As discussed w/ @annescharf

**Comment by andreakoelzsch** [comment]
Hi Clemens and Anne, the csv handling is not necessary in this part of the SDK, yes. The only place where it is necessary to read csv is in the Cloud Storage App (so far), where it is working good. Thanks!

**Comment by cleemansen** [comment]
Thanks for the clarification. I will remove the fallback handling `move::move(sourceFile, removeDuplicatedTimestamps=TRUE)` from the SDK (aka from the calling code of any future app on MoveApps).
